Default 2nd arg of RobustChannel._on_channel_close to None
Without doing this the _on_channel_close method raises an error when
called without the 2nd arg specified.

tools.py:168  Callback error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/aio_pika/tools.py", line 166, in __call__
    cb(self.__sender(), *args, **kwargs)
TypeError: _on_channel_close() missing 1 required positional argument: 'exc'